package com.facebook.graphql;

public final class GraphQlQueryCallOrderby1 extends GraphQlQueryBaseFieldCallImpl
  implements GraphQlQueryCommentsConnection.CallOnCommentsConnection, GraphQlQueryContactsConnection.CallOnContactsConnection, GraphQlQueryFriendListMembersConnection.CallOnFriendListMembersConnection, GraphQlQueryFriendListsConnection.CallOnFriendListsConnection, GraphQlQueryFriendsConnection.CallOnFriendsConnection, GraphQlQueryFriendsHereNowConnection.CallOnFriendsHereNowConnection, GraphQlQueryFriendsWhoLikeConnection.CallOnFriendsWhoLikeConnection, GraphQlQueryFriendsWhoVisitedConnection.CallOnFriendsWhoVisitedConnection, GraphQlQueryGiftProductCategoryToProductsConnection.CallOnGiftProductCategoryToProductsConnection, GraphQlQueryGiftProductsConnection.CallOnGiftProductsConnection, GraphQlQueryGroupMembersConnection.CallOnGroupMembersConnection, GraphQlQueryHomeStoriesConnection.CallOnHomeStoriesConnection, GraphQlQueryInterestListsConnection.CallOnInterestListsConnection, GraphQlQueryLikedProfilesConnection.CallOnLikedProfilesConnection, GraphQlQueryLikersOfContentConnection.CallOnLikersOfContentConnection, GraphQlQueryMutualFriendsConnection.CallOnMutualFriendsConnection, GraphQlQueryNewsFeedConnection.CallOnNewsFeedConnection, GraphQlQueryPhotosTakenHereByFriendsConnection.CallOnPhotosTakenHereByFriendsConnection, GraphQlQueryRecommendedApplicationsConnection.CallOnRecommendedApplicationsConnection
{
  GraphQlQueryCallOrderby1(GraphQlQueryParam paramGraphQlQueryParam)
  {
    super("orderby", new GraphQlQueryParam[] { paramGraphQlQueryParam });
  }
}

/* Location:           /data1/software/apk2java/dex2jar-0.0.9.12/secondary-1.dex_dex2jar.jar
 * Qualified Name:     com.facebook.graphql.GraphQlQueryCallOrderby1
 * JD-Core Version:    0.6.2
 */